name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'Batchbrake/Batchbrake.csproj'
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Batchbrake v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          body: |
            # Batchbrake v${{ steps.get_version.outputs.version }}
            
            ## What's New
            - 
            
            ## Features
            - Batch video conversion with HandBrakeCLI
            - Drag & drop interface
            - 90+ built-in presets plus custom preset support
            - Parallel processing capabilities
            - Windows support (x64, x86, ARM64)
            
            ## Installation
            
            ### Windows
            - Download the appropriate version for your system:
              - `Batchbrake-Windows-win-x64.zip` for 64-bit systems
              - `Batchbrake-Windows-win-x86.zip` for 32-bit systems
              - `Batchbrake-Windows-win-arm64.zip` for ARM64 systems
            - Extract and run `Batchbrake.exe`
            - Ensure HandBrakeCLI is installed
            
            ## Requirements
            - HandBrakeCLI must be installed separately
            - FFmpeg (optional) for enhanced metadata extraction
            
            ## Checksums
            See checksums.txt for SHA256 hashes of all release files.

  build-windows:
    needs: create-release
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win-x64, win-x86, win-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build and Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} `
            -c Release `
            -r ${{ matrix.runtime }} `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:EnableCompressionInSingleFile=true `
            -p:PublishTrimmed=false `
            -p:Version=${{ needs.create-release.outputs.version }} `
            -o ./publish/${{ matrix.runtime }}
            
      - name: Create Archive
        run: |
          cd publish/${{ matrix.runtime }}
          Compress-Archive -Path * -DestinationPath ../../Batchbrake-Windows-${{ matrix.runtime }}.zip
          
      - name: Calculate SHA256
        run: |
          $hash = Get-FileHash -Path Batchbrake-Windows-${{ matrix.runtime }}.zip -Algorithm SHA256
          "$($hash.Hash)  Batchbrake-Windows-${{ matrix.runtime }}.zip" | Out-File -FilePath checksums-windows-${{ matrix.runtime }}.txt
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Batchbrake-Windows-${{ matrix.runtime }}.zip
          asset_name: Batchbrake-Windows-${{ matrix.runtime }}.zip
          asset_content_type: application/zip
          
      - name: Upload Checksums
        uses: actions/upload-artifact@v3
        with:
          name: checksums
          path: checksums-windows-${{ matrix.runtime }}.txt


  finalize-release:
    needs: [create-release, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download all checksums
        uses: actions/download-artifact@v3
        with:
          name: checksums
          
      - name: Combine checksums
        run: |
          cat checksums-*.txt > checksums.txt
          echo "SHA256 Checksums for all release files:" | cat - checksums.txt > temp && mv temp checksums.txt
          
      - name: Upload combined checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain